---
- hosts: macos_servers
  gather_facts: false

  pre_tasks:
    - when: inventory_hostname == "localhost"
      set_fact:
        ansible_connection: local
        ansible_python_interpreter: "{{ ansible_playbook_python }}"

  roles:
    - role: brew
