---
- name: update brew cache
  become: no
  homebrew:
    update_homebrew: yes
    upgrade_all: no
  changed_when: false

- name: be sure if each tap repository is present
  become: no
  homebrew_tap:
    name: "{{ item }}"
    state: present
  loop:
    - homebrew/cask
    - homebrew/cask-fonts
    - beeftornado/rmtree

- name: be sure if each basic package is present
  become: no
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - ansible
    - stow
    - unzip
    - wget
    - cmake
    - tree
    - ghq
    - tmux
    - tig
    - zsh
    - zsh-completions
    - zsh-autosuggestions
    - fzf
    - minikube

- name: be sure if each nvim-related package is present
  become: no
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - neovim
    - clang-format
    - black
    - stylua
    - shfmt
    - ripgrep
    - fd

- name: be sure if each nvim-related pip module is present
  become: no
  pip:
    executable: pip3
    extra_args: "--user --upgrade"
    name:
      - pynvim
      - codespell
    state: present

- name: be sure if each oai-related package is present
  become: no
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - scrcpy

- name: be sure if each cask package is present
  become: no
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
    - iterm2
    - font-hack-nerd-font
    - slack
    - brave-browser
    - notion
    - maestral
    - appcleaner
    - kindle
    - jasper
    - visual-studio-code
    - toggl-track
    - zoom
    - karabiner-elements
    - soulver
